import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/components/auth-provider";
import { ExtensionErrorSuppressor } from "@/components/extension-error-suppressor";
import { ClipboardPolyfillProvider } from "@/components/clipboard-polyfill-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "assistant-ui Starter App",
  description: "Generated by create-assistant-ui",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              // Clipboard polyfill - runs immediately before React hydration
              if (typeof navigator !== 'undefined' && !navigator.clipboard) {
                navigator.clipboard = {
                  writeText: async function(text) {
                    const textArea = document.createElement('textarea');
                    textArea.value = text;
                    textArea.style.position = 'fixed';
                    textArea.style.left = '-999999px';
                    textArea.style.top = '-999999px';
                    textArea.style.opacity = '0';
                    document.body.appendChild(textArea);
                    textArea.focus();
                    textArea.select();
                    try {
                      const successful = document.execCommand('copy');
                      document.body.removeChild(textArea);
                      if (!successful) throw new Error('Copy failed');
                    } catch (error) {
                      document.body.removeChild(textArea);
                      throw error;
                    }
                  },
                  readText: async function() {
                    throw new Error('readText not supported');
                  }
                };
              } else if (typeof navigator !== 'undefined' && navigator.clipboard && !navigator.clipboard.writeText) {
                navigator.clipboard.writeText = async function(text) {
                  const textArea = document.createElement('textarea');
                  textArea.value = text;
                  textArea.style.position = 'fixed';
                  textArea.style.left = '-999999px';
                  textArea.style.top = '-999999px';
                  textArea.style.opacity = '0';
                  document.body.appendChild(textArea);
                  textArea.focus();
                  textArea.select();
                  try {
                    const successful = document.execCommand('copy');
                    document.body.removeChild(textArea);
                    if (!successful) throw new Error('Copy failed');
                  } catch (error) {
                    document.body.removeChild(textArea);
                    throw error;
                  }
                };
              }
            `,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClipboardPolyfillProvider />
        <ExtensionErrorSuppressor />
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
